"""Safe append-only progress events for observable review jobs."""

from __future__ import annotations

import re
from collections.abc import Callable
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any

from app.pipeline import sanitize_error

ProgressCallback = Callable[[str, str, str, str, dict[str, Any] | None], None]

TERMINAL_RUN_STATUSES = frozenset({"READY_FOR_HUMAN_REVIEW", "FAILED", "INTERRUPTED"})
EVENT_STATUSES = frozenset({"pending", "running", "completed", "partial", "skipped", "failed"})
ALLOWED_DETAIL_KEYS = frozenset(
    {
        "document_role", "document_status", "section_count", "table_count", "span_count",
        "parameter_name", "normalized_value", "normalized_unit", "parameter_count",
        "normalized_fact_count", "deduplicated_fact_count", "applicable_rule_count",
        "not_applicable_rule_count", "rule_id", "result", "evidence_count",
        "selected_span_count", "candidate_count", "valid_count", "rejected_count",
        "original_evidence_count", "selected_character_count", "ai_coverage_ratio",
        "available_span_count", "coverage_ratio", "validation_reason_code",
        "http_status", "response_character_count", "stop_reason", "content_block_count",
        "rule_finding_count", "llm_finding_count", "final_finding_count",
        "needs_human_review", "provider", "cache_hit", "completed_rule_count",
        "retry_attempt", "provider_error_code",
        "batch_count", "batch_index", "deduplicated_finding_count",
        "premerge_finding_count", "postmerge_finding_count",
    }
)
_IDENTIFIER_KEYS = frozenset({
    "rule_id", "provider", "document_role", "document_status", "result",
    "validation_reason_code", "stop_reason", "provider_error_code",
})
_SAFE_RESPONSE_DETAIL_KEYS = frozenset({"response_character_count", "content_block_count"})
_FORBIDDEN_KEY_RE = re.compile(
    r"(?i)(api.?key|token|secret|password|prompt|response|request|body|content|text|path|trace|stack)"
)


@dataclass(frozen=True)
class ProgressEvent:
    sequence: int
    stage: str
    event_type: str
    status: str
    message: str
    details: dict[str, Any]
    created_at: datetime


def safe_progress_payload(
    stage: str,
    event_type: str,
    status: str,
    message: str,
    details: dict[str, Any] | None = None,
) -> tuple[str, str, str, str, dict[str, Any]]:
    if not re.fullmatch(r"[A-Z][A-Z0-9_]{0,63}", stage):
        raise ValueError("invalid progress stage")
    if not re.fullmatch(r"[A-Z][A-Z0-9_]{0,63}", event_type):
        raise ValueError("invalid progress event type")
    if status not in EVENT_STATUSES:
        raise ValueError("invalid progress status")
    if not isinstance(message, str) or not message.strip() or len(message) > 500:
        raise ValueError("progress message must be bounded")
    safe_message = sanitize_error(message, max_length=500)
    # ``[path]`` is generated by our own sanitizer and is safe to persist.  It
    # must not be rejected by the subsequent sensitive-content check.
    message_for_scan = safe_message.replace("[path]", "")
    if _FORBIDDEN_KEY_RE.search(message_for_scan):
        raise ValueError("progress message contains prohibited content")
    output: dict[str, Any] = {}
    for key, value in (details or {}).items():
        if key not in ALLOWED_DETAIL_KEYS or (
            key not in _SAFE_RESPONSE_DETAIL_KEYS and _FORBIDDEN_KEY_RE.search(key)
        ):
            raise ValueError("progress details contain a prohibited key")
        if isinstance(value, bool):
            output[key] = value
        elif isinstance(value, int) and value >= 0:
            output[key] = value
        elif isinstance(value, float):
            output[key] = value
        elif key in _IDENTIFIER_KEYS and isinstance(value, str) and len(value) <= 128:
            output[key] = value
        elif key in {"parameter_name", "normalized_unit"} and isinstance(value, str) and len(value) <= 128:
            output[key] = value
        else:
            raise ValueError(f"unsafe progress detail: {key}")
    return stage, event_type, status, safe_message, output


def utc_now() -> datetime:
    return datetime.now(timezone.utc)
